#!/bin/bash --
# Copyright (c) 2017, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -e

dartfmt -w $(find bin lib test -name \*.dart 2>/dev/null)
pub get
pub upgrade
dartanalyzer \
    --enable-experiment=non-nullable \
    --fatal-warnings \
    --fatal-infos \
    $(find bin lib test -name \*.dart 2>/dev/null)

# pub run test doesn't support NNBD yet.
for src in $(find test -name \*.dart); do
  grep -q 'main()' "$src" || continue
  echo "$src in sound mode."
  dart --enable-experiment=non-nullable --null-safety "$src" || exit 1
  echo "$src in unsound mode."
  dart --enable-experiment=non-nullable "$src" || exit 1
done
